package com.scriptoria.browser

import android.app.Application
import android.app.NotificationChannel
import android.app.NotificationManager
import android.os.Build
import androidx.room.Room
import com.scriptoria.browser.data.database.AppDatabase
import com.scriptoria.browser.data.repository.GmStorageRepository
import com.scriptoria.browser.data.repository.ScriptRepository
import com.scriptoria.browser.data.storage.ScriptFileStore
import com.scriptoria.browser.engine.executor.RequireManager
import com.scriptoria.browser.engine.executor.UserscriptManager
import okhttp3.OkHttpClient
import java.util.concurrent.TimeUnit

class ScriptoriaApp : Application() {

    lateinit var database: AppDatabase
        private set
    lateinit var fileStore: ScriptFileStore
        private set
    lateinit var scriptRepository: ScriptRepository
        private set
    lateinit var gmStorageRepository: GmStorageRepository
        private set
    lateinit var httpClient: OkHttpClient
        private set
    lateinit var requireManager: RequireManager
        private set
    lateinit var userscriptManager: UserscriptManager
        private set
    lateinit var downloadPreferences: com.scriptoria.browser.data.preferences.DownloadPreferences
        private set
    lateinit var downloadManagerRepository: com.scriptoria.browser.data.repository.DownloadManagerRepository
        private set

    override fun onCreate() {
        super.onCreate()
        instance = this

        createNotificationChannel()

        database = Room.databaseBuilder(
            applicationContext,
            AppDatabase::class.java,
            "scriptoria_browser.db"
        ).fallbackToDestructiveMigration().build()

        fileStore = ScriptFileStore(this)
        scriptRepository = ScriptRepository(database.scriptDao(), fileStore)
        gmStorageRepository = GmStorageRepository(database.gmStorageDao())

        httpClient = OkHttpClient.Builder()
            .connectTimeout(15, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .followRedirects(true)
            .followSslRedirects(true)
            .build()

        requireManager = RequireManager(fileStore, httpClient)
        userscriptManager = UserscriptManager(this, scriptRepository, gmStorageRepository, requireManager, httpClient)
        downloadPreferences = com.scriptoria.browser.data.preferences.DownloadPreferences(this)
        downloadManagerRepository = com.scriptoria.browser.data.repository.DownloadManagerRepository(this, downloadPreferences)

        // Nothing can be mid-transfer at process start, so any leftover progress notification
        // or pending file belongs to a download that died with the previous process.
        com.scriptoria.browser.engine.network.StreamDownloads.clearOrphans(this)
    }

    private fun createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                NOTIFICATION_CHANNEL_ID,
                "Userscript Notifications",
                NotificationManager.IMPORTANCE_DEFAULT
            ).apply {
                description = "Notifications generated by installed userscripts"
            }
            val notificationManager = getSystemService(NotificationManager::class.java)
            notificationManager?.createNotificationChannel(channel)
        }
    }

    companion object {
        const val NOTIFICATION_CHANNEL_ID = "userscript_notifications"
        lateinit var instance: ScriptoriaApp
            private set
    }
}
